export enum As {
    // Design = 'design',
    Item = 'item',
    ItemConsumable = 'itemConsumable',
    ItemEquipment = 'itemEquipment',
    Knowledge = 'knowledge',
    MaterialGroup = 'materialGroup',
    NPC = 'npc',
    NPCOther = 'npcOther',
    NPCWorker = 'npcWorker',
    Processing = 'processing',
    Quest = 'quest',
    Recipe = 'recipe',
    // WorkerSkill = 'workerSkill',
}