export enum Classes {
    Archer = 'archer',
    Berserker = 'berserker',
    DarkKnight = 'darkKnight',
    Kunoichi = 'kunoichi',
    Lahn = 'lahn',
    Maehwa = 'maehwa',
    Musa = 'musa',
    Mystic = 'mystic',
    Ninja = 'ninja',
    Ranger = 'ranger',
    Sorceress = 'sorceress',
    Striker = 'striker',
    Tamer = 'tamer',
    Valkyrie = 'valkyrie',
    Warrior = 'warrior',
    Witch = 'witch',
    Wizard = 'wizard',
}