export enum Attributes {
    HP = 'hp',
    MP = 'mp',
    Damage = 'damage',
    Defense = 'defense',
    Accuracy = 'accuracy',
    Evasion = 'evasion',
    DamageReduction = 'damageReduction',
    BonusDamage = 'bonusDamage',
    BonusDefense = 'bonusDefense',
    BonusAccuracy = 'bonusAccuracy',
    BonusEvasion = 'bonusEvasion',
    BonusDamageReduction = 'bonusDamageReduction',
}

export enum Classes {
    Archer = 'archer',
    Berserker = 'berserker',
    DarkKnight = 'darkKnight',
    Kunoichi = 'kunoichi',
    Lahn = 'lahn',
    Maehwa = 'maehwa',
    Musa = 'musa',
    Mystic = 'mystic',
    Ninja = 'ninja',
    Ranger = 'ranger',
    Sorceress = 'sorceress',
    Striker = 'striker',
    Tamer = 'tamer',
    Valkyrie = 'valkyrie',
    Warrior = 'warrior',
    Witch = 'witch',
    Wizard = 'wizard',
}
